### ISSUE TITLE
Is it possible to support multiple lines?

### ISSUE THREAD

**Issue by yuki-takei** [joel-porquet/CodeMirror-markdown-list-autoindent#1]
Hi. Thank you for providing an awesome patch.

Request
---------

Is it possible to support multiple lines?

![gif](https://user-images.githubusercontent.com/1638767/34788554-447db9bc-f67e-11e7-9f19-778c57186d68.gif)

(This is a capture of Visual Studio Code)

**Comment by joel-porquet** [comment]
Well, actually code-mirror supports multi-cursors: while holding the Ctrl key, you can click at various locations in your text and have multiple cursors appear. Maybe can you try that in order to support the indentation of multiple lines?

(otherwise, I'm actually not using code-mirror anymore so this patch is mostly un-maintained. I just published  it in case it interests other people)
